Conatiners separate the application runtime environment from the hosting
OS. In addtion to the usual benefits of containerizing an application, this
means you can provide older software to newer systems.

In this lab, you will be installing additional software into the
container image, however that software runs as an interactive
application. So you do not need `+systemd+` for managing services 
within the running container. This means you can use the 
*Standard* UBI image (as opposed to the Minimal or
Multi-service images). The sofware needed is packaged as an RPM
and can be directly installed from the repository via `dnf`.

The Red Hat Universal Base Image (UBI) is produced by Red Hat and is an
easy place to start when containerizing applications. If you want to
read more about the UBI program, or the three different flavors of UBI,
check out the https://developers.redhat.com/articles/ubi-faq[FAQ -
Universal Base Images] for additional details.

By executing the command below, your system will download the Standard
UBI image from Red Hat’s registry.

[source,bash,run]
----
buildah from registry.access.redhat.com/ubi9/ubi
----

From the output above, you can see that the image was successfully
downloaded and a working container image was created and attached to the
system with the name of *ubi-working-container*. You will use this
working container in the next steps to install additional software
packages into the image.
