At this point, the container is configured. It is time to transition
from a working container into a committed image. In the command below,
you will use the `+buildah+` command to commit the working container to
an image called: `+moon-buggy+`.

[source,bash,run]
----
buildah commit ubi-working-container moon-buggy
----

The above output shows that the commit was successful, however you can
verify this by looking at the available container images on the system.

[source,bash,run]
----
podman image list
----

Notice in the output above that `+moon-buggy+` is the first container
image listed in the `+podman image list+` output.

Buildah also has access to local container storage, and shows the same 
view as podman.

[source,bash,run]
----
buildah images
----

However, they have different views of active containers. The working
container `ubi-working-container` is only visible to `buildah`. It's
good practice to clean up the working containers when using `buildah`
this way.

[source,bash,run]
----
buildah ps -a
podman ps -a
----
