In the previous step, you committed your container image. You can look
at the images in local container storage by using
`+podman image list+`.

[source,bash,run]
----
podman image list
----

Now that the image is available, you can run the container. Because this
application is managed by a service, you will use the `+-d+` option to
run the container in a detatched mode. Additionally, you will map
traffic coming to port 8080 on the host system to be routed to the
application running on the container’s port 80.

[source,bash,run]
----
podman run -d -p 8080:80 clumsy-bird
----

You can now access the http://rhel.{guid}.{domain}[running `+clumsy-bird+` application,window=_blank]
or copy the link below to a new window.

[source,sh,subs=attributes+]
----
http://rhel.{guid}.{domain}
----

You've now used `buildah` to add application source code and RPM packaged software 
to a container image, as well as adding configurations to the container. You should 
be able to use `buildah` to generate an image for any application and dependencies 
from any source. 
