---
virtualmachines:
  - name: "rhel"
    image: "rhel-10.0"
    bootloader: efi
    memory: "2G"
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
    userdata: |
      #cloud-config
      fqdn: rhel.lab
      hostname: rhel
      prefer_fqdn_over_hostname: true
      manage_etc_hosts: true

