---
containers:
  - name: gitea
    image: gitea/gitea:1.16.8-rootless
    ports:
      - name: gitea
        containerPort: 3000
        protocol: TCP
    environment:
      GITEA__DEFAULT__RUN_MODE: dev
      GITEA__database__DB_TYPE: sqlite3
      GITEA__database__PATH: /data/gitea/gitea.db
      GITEA__picture__DISABLE_GRAVATAR: "true"
      GITEA__repository__DEFAULT_PRIVATE: "false"
      GITEA__repository__DEFAULT_PUSH_CREATE_PRIVATE: "false"
      GITEA__repository__ENABLE_PUSH_CREATE_ORG: "true"
      GITEA__repository__ENABLE_PUSH_CREATE_USER: "true"
      GITEA__repository__ONLY_ALLOW_PUSH_IF_GITEA_ENVIRONMENT_SET: "false"
      GITEA__security__INSTALL_LOCK: "true"
      GITEA__server__SSH_DOMAIN: http://gitea
      GITEA__service__DISABLE_REGISTRATION: "true"
      GITEA__service__REQUIRE_SIGNIN_VIEW: "false"
      GITEA__webhook__ALLOWED_HOST_LIST: '*'
    volumeMounts:
      - name: gitea-varlib
        mountPath: /var/lib/gitea/
      - name: gitea-data
        mountPath: /data/
      - name: gitea-etc
        mountPath: /etc/gitea
    volumes:
      - name: gitea-data
        emptyDir: {}
      - name: gitea-etc
        emptyDir: {}
      - name: gitea-varlib
        emptyDir: {}
    commands: 
        - gitea admin user create --admin --username gitea --password gitea --email dummy@dummy.com --must-change-password=false
        - >
          curl -X POST -H "accept: application/json" -H "Content-Type: application/json"
          -u 'gitea:gitea' 
          -d '{"username": "student", "full_name": "student", "description": "student"}'
          http://localhost:3000/api/v1/orgs
        - >
          curl -X POST -H "accept: application/json" -H "Content-Type: application/json"
          -u 'gitea:gitea'
          -d '{"clone_addr": "https://github.com/ellisonleao/clumsy-bird", "repo_name": "clumsy-bird", "owner": "student", "uid": 2, "private": false}'
          http://localhost:3000/api/v1/repos/migrate
    memory: 2Gi
    services:
      - name: gitea
        ports:
          - port: 3000
            protocol: TCP
            targetPort: 3000
            name: gitea
    routes:
      - name: gitea
        host: gitea
        service: gitea
        targetPort: 3000
        tls: true
        tls_termination: Edge
virtualmachines:
  - name: "rhel"
    image: "rhel-10-0-07-09-25-3"
    bootloader: efi
    memory: "2G"
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
    services:
      - name: rhel
        ports:
          - port: 8080
            protocol: TCP
            targetPort: 8080
            name: rhel
    routes:
      - name: rhel
        host: rhel
        service: rhel
        targetPort: 8080
        tls: false

