---
virtualmachines:
  - name: "rhel"
    image: "rhel-10-0-07-09-25-3"
    bootloader: efi
    memory: "4G"
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
    services:
      - name: rhel
        ports:
          - port: 8080
            protocol: TCP
            targetPort: 8080
            name: rhel
    routes:
      - name: rhel
        host: rhel
        service: rhel
        targetPort: 8080
        tls: false

