---
virtualmachines:
  - name: "rhel"
    image: "rhel-10-0-07-09-25-3"
    bootloader: efi
    memory: "2G"
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
    services:
      - name: rhel-http
        ports:
          - port: 80
            protocol: TCP
            targetPort: 80
            name: rhel-http
    routes:
      - name: rhel-http
        host: rhel
        service: rhel-http
        targetPort: 80
        tls: false

